### ISSUE TITLE
How to install on macos?

### ISSUE THREAD

**Issue by arainot** [asdolo/gba-sleephack#1]
@asdolo Trying to install this on macos says that it is just a document. How do I install this? I have homebrew installed if it helps.

**Comment by asdolo** [comment]
> @asdolo Trying to install this on macos says that it is just a document. How do I install this? I have homebrew installed if it helps.

Download the zip and extract it. Make sure to make the binary file executable:

```bash
chmod +x gba-sleephack-patcher-tool
```

Then just run it:

```bash
./gba-sleephack-patcher-tool
```

**Comment by arainot** [comment]
That works! Thanks! Would be useful to put this into the readme. I have another question but I'll open a separate ticket.
